# Generated by Django 4.0.3 on 2022-03-20 09:30

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_clothing_length_clothing_ptp_clothing_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('length', models.CharField(max_length=200, null=True)),
                ('ptp', models.CharField(max_length=200, null=True)),
                ('sold', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.path_and_rename)),
            ],
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
