# Generated by Django 4.0.3 on 2022-03-20 17:23

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_tees_delete_clothing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusive_Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('length', models.CharField(max_length=200, null=True)),
                ('ptp', models.CharField(max_length=200, null=True)),
                ('sold', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Hoodies_Sweaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('length', models.CharField(max_length=200, null=True)),
                ('ptp', models.CharField(max_length=200, null=True)),
                ('sold', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('waist', models.CharField(max_length=200, null=True)),
                ('inseam', models.CharField(max_length=200, null=True)),
                ('rise', models.CharField(max_length=200, null=True)),
                ('sold', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.path_and_rename)),
            ],
        ),
    ]
